services:

  storage_redis:
    image: redis
    volumes:
      - ./data/redis:/data

  counter:
    image: node:22.5
    working_dir: /app
    volumes:
      - ./counter:/app
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage_redis
    command: npm run dev  
    depends_on:
      - storage_redis

  storage_mongo:
    image: mongo 
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: library
    volumes:
      - ./data/mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro 

  library:
    image: node:22.5
    working_dir: /app
    volumes:
      - ./library:/app
    environment: 
      - COUNTER_URL=http://counter:3001
      - MONGO_URL=mongodb://storage_mongo:27017/library
    env_file:
      - .env  
    ports:
      - 80:${PORT}
    command: npm run dev
    depends_on:
      - counter
      - storage_mongo 