services:

  storage_mongo:
    image: mongo 
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: avito
    volumes:
      - ./src/db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro 

  avito:
    image: node:22.5
    working_dir: /app
    volumes:
      - .:/app
    environment: 
      - MONGO_URL=mongodb://storage_mongo:27017/avito
    env_file:
      - .env  
    ports: 
      - 80:${PORT}
    command: npm run dev
    depends_on: 
      - storage_mongo 