services:

  storage_mongo:
    image: mongo 
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: avito
    volumes:
      - ./src/db/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro 

  avito:
    build: .
    ports: 
      - 80:${PORT}
    environment: 
      - MONGO_URL=mongodb://storage_mongo:27017/avito
    env_file:
      - .env
    depends_on: 
      - storage_mongo 